/**
 * financialInputIdentity.js — financial_input_identity_v1 canonicalization.
 *
 * FROZEN CONTRACT (V2-HARNESS-SAFETY-AND-STRATEGY-DEDUP-01). v1 identities are persisted and
 * must stay reproducible from historical diagnoses.input_snapshot. Do not edit this file or
 * server/modules/diagnosis/financialIdentity.js: any change to fields, canonicalization,
 * serialization or hashing ships as financial_input_identity_v2 next to v1, never in place.
 * Pinned by golden vectors and source hashes in server/bin/financial-identity-golden-test.js.
 *
 * One canonical form of the EngineInput facts the V2 classifier consumes, plus the
 * positional meaning of debt_index. Same canonical string ⇔ same classifier input.
 * The server owns the identity (sha256 of the canonical string, see
 * server/modules/diagnosis/financialIdentity.js); the browser only uses the canonical
 * string to bind its V2 state to the input it was computed for. It never sends it.
 *
 * Rules (FINANCIAL-INPUT-IDENTITY-V1):
 * - Amounts follow the classifier parseAmount: finite number, or trimmed string matching
 *   /^-?\d+(\.\d+)?$/ (dot decimal only). Canonical = plain decimal, full precision, no
 *   leading/trailing zeros, "-0" → "0". Anything else → null (blank and invalid alike).
 * - Expenses: blank and zero contribute nothing and are omitted; invalid or negative →
 *   "!invalid" (it makes the total unknown). gastos by sorted key, custom in array order.
 * - Debts keep their array order: the index IS debt_index. Never sorted.
 * - Enum strings (situacion_ui, estado, pago_clarificacion) are kept exact: the classifier
 *   copies them verbatim into canonical_facts provenance.
 * - Creditor text: NFKC, trim, internal whitespace collapsed, lowercase; empty → null.
 */
(function (root, factory) {
  var api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.CZFinancialInputIdentity = api;
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  var VERSION = "financial_input_identity_v1";
  var INVALID = "!invalid";
  var INVALID_ENTRY = "!invalid_entry";
  var PAID = "!paid_or_cancelled";
  var AMOUNT_RE = /^-?\d+(\.\d+)?$/;

  function isPlainObject(v) {
    return !!v && typeof v === "object" && !Array.isArray(v);
  }

  function isBlankAmount(raw) {
    return raw == null || (typeof raw === "string" && raw.trim() === "");
  }

  function normalizeDecimalString(s) {
    var neg = s.charAt(0) === "-";
    if (neg) s = s.slice(1);
    var dot = s.indexOf(".");
    var intPart = dot === -1 ? s : s.slice(0, dot);
    var frac = dot === -1 ? "" : s.slice(dot + 1);
    intPart = intPart.replace(/^0+/, "") || "0";
    frac = frac.replace(/0+$/, "");
    var out = frac ? intPart + "." + frac : intPart;
    if (out === "0") return "0";
    return neg ? "-" + out : out;
  }

  function expandExponent(s) {
    var m = /^(-?)(\d+)(?:\.(\d+))?e([+-]?\d+)$/i.exec(s);
    if (!m) return null;
    var digits = m[2] + (m[3] || "");
    var point = m[2].length + parseInt(m[4], 10);
    if (point <= 0) {
      digits = new Array(2 - point).join("0") + digits;
      point = 1;
    } else if (point > digits.length) {
      digits = digits + new Array(point - digits.length + 1).join("0");
    }
    return m[1] + digits.slice(0, point) + (point < digits.length ? "." + digits.slice(point) : "");
  }

  /** Canonical decimal string of a classifier-parseable amount, or null. */
  function canonicalAmount(raw) {
    if (typeof raw === "number") {
      if (!Number.isFinite(raw)) return null;
      if (raw === 0) return "0";
      var s = String(raw);
      if (/e/i.test(s)) s = expandExponent(s);
      return s == null ? null : normalizeDecimalString(s);
    }
    if (typeof raw !== "string") return null;
    var t = raw.trim();
    if (!AMOUNT_RE.test(t)) return null;
    return normalizeDecimalString(t);
  }

  function isNegative(c) {
    return c.charAt(0) === "-";
  }

  function canonicalExpense(raw) {
    if (isBlankAmount(raw)) return null;
    var c = canonicalAmount(raw);
    if (c == null || isNegative(c)) return INVALID;
    return c === "0" ? null : c;
  }

  function canonicalText(raw) {
    if (raw == null) return null;
    var s = String(raw);
    if (typeof s.normalize === "function") s = s.normalize("NFKC");
    s = s.replace(/\s+/g, " ").trim().toLowerCase();
    return s === "" ? null : s;
  }

  function exactString(v) {
    return typeof v === "string" ? v : null;
  }

  function incomePrefillUnconfirmed(entryContext) {
    if (!isPlainObject(entryContext) || !isPlainObject(entryContext.field_provenance)) return false;
    var fp = entryContext.field_provenance;
    var meta = isPlainObject(fp.ingreso) ? fp.ingreso : isPlainObject(fp.declared_ingreso) ? fp.declared_ingreso : null;
    if (!meta) return false;
    var source = typeof meta.source === "string" ? meta.source : null;
    var detail = typeof meta.detail === "string" ? meta.detail : null;
    var handoffDeclared = source === "handoff" && detail === "handoff";
    var isPrefill = !handoffDeclared && (source === "url_prefill" || source === "handoff" || detail === "handoff");
    return isPrefill && meta.user_modified !== true;
  }

  function canonicalDebt(d) {
    if (!isPlainObject(d)) return INVALID_ENTRY;
    if (d.cancelada === true || d.situacion_ui === "pagada") return PAID;
    var sit = exactString(d.situacion_ui);
    var sitUsed = sit != null && sit.trim() !== "";
    var sitKind = sitUsed ? sit.trim() : null;
    return [
      typeof d.tipo === "string" ? d.tipo.trim() || null : null,
      canonicalText(d.acreedor_raw != null ? d.acreedor_raw : d.acreedor),
      canonicalAmount(d.monto),
      canonicalAmount(d.pago),
      sitUsed ? sit : null,
      sitUsed ? null : exactString(d.estado),
      sitKind === "atrasado_pagando" ? canonicalAmount(d.ultimo_pago_declarado) : null,
      sitKind === "pagando_normal" && typeof d.pago_clarificacion === "string" && d.pago_clarificacion
        ? d.pago_clarificacion
        : null,
    ];
  }

  /** Canonical JSON string (fixed positions, no object key order involved). */
  function canonicalizeFinancialInput(input) {
    if (!isPlainObject(input)) return null;
    var gastos = isPlainObject(input.gastos) ? input.gastos : {};
    var expenses = [];
    Object.keys(gastos).sort().forEach(function (k) {
      var c = canonicalExpense(gastos[k]);
      if (c != null) expenses.push([k, c]);
    });
    var custom = [];
    (Array.isArray(input.custom_expenses) ? input.custom_expenses : []).forEach(function (c) {
      if (!isPlainObject(c) || c.included === false || c._included === false) return;
      var v = canonicalExpense(c.amount != null ? c.amount : c.monto);
      if (v != null) custom.push(v);
    });
    return JSON.stringify([
      VERSION,
      canonicalAmount(input.ingreso != null ? input.ingreso : input.declared_ingreso),
      incomePrefillUnconfirmed(input.entry_context),
      expenses,
      custom,
      input.no_debts_declared === true,
      (Array.isArray(input.deudas) ? input.deudas : []).map(canonicalDebt),
    ]);
  }

  return {
    FINANCIAL_INPUT_IDENTITY_VERSION: VERSION,
    canonicalAmount: canonicalAmount,
    canonicalText: canonicalText,
    canonicalizeFinancialInput: canonicalizeFinancialInput,
  };
});
